"""fix stu_age to date

Revision ID: 592745b9e3ef
Revises: ccfef3ef4054
Create Date: 2026-05-30 21:46:20.572812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592745b9e3ef'
down_revision = 'ccfef3ef4054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('stu_age',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('stu_age',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
