"""student-age

Revision ID: 835f97e3b173
Revises: e7271b3cec29
Create Date: 2026-03-10 09:54:33.035538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835f97e3b173'
down_revision = 'e7271b3cec29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
