"""student-age

Revision ID: e7271b3cec29
Revises: 9f2a61f3f228
Create Date: 2026-03-06 17:00:43.703383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7271b3cec29'
down_revision = '9f2a61f3f228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('stu_age',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('stu_age',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
